#!/bin/bash

make all # > /dev/null 2>&1
if [ ! -x ./tsp ]
then
    exit 1
fi

rm -f ./output/out-Random-progression.txt
rm -f ./output/out-Random-path.txt 
rm -f ./output/out-Christofides-progression.txt
rm -f ./output/out-Christofides-path.txt
rm -f ./output/out-SAHC-progression.txt
rm -f ./output/out-SAHC-path.txt
rm -f ./output/out-RMHC-progression.txt
rm -f ./output/out-RMHC-path.txt
rm -f ./output/out-RSGA-progression.txt
rm -f ./output/out-RSGA-path.txt
rm -f ./output/out-Random-progression-lt.txt
rm -f ./output/out-Random-path-lt.txt 
rm -f ./output/out-Christofides-progression-lt.txt
rm -f ./output/out-Christofides-path-lt.txt
rm -f ./output/out-SAHC-progression-lt.txt
rm -f ./output/out-SAHC-path-lt.txt
rm -f ./output/out-RMHC-progression-lt.txt
rm -f ./output/out-RMHC-path-lt.txt
rm -f ./output/out-RSGA-progression-lt.txt
rm -f ./output/out-RSGA-path-lt.txt

file=

# if no file was passed to the script and res/tsp.txt exists
if [ "$#" -lt 1 -a -e ./res/tsp.txt ]
then
    file=./res/tsp.txt
elif [ -e $1 ]
then
    file=$1
else
    echo "no valid file to use" 1>&2
    exit 1
fi

# make sure file has correct line endings
dos2unix $file > /dev/null 2>&1

# make output directory in case it does not exist
mkdir ./output > /dev/null 2>&1

# number of times to run the program
re='^[0-9]+$'
num_trials=
if [ "$#" -lt 2 ]
then
    num_trials=40  # default
elif ! [[ $2 =~ $re ]]
then
    echo "number of trials must be a valid integer"
else
    num_trials=$2
fi

counter=0
while [ $counter -lt $num_trials ]
do
    echo
    python3 ./src/christofides/christofides.py $file &
    ./tsp $file
    ((counter++))
    wait
    sleep 1
done 

echo
python3 ./src/graph-progression.py \
        ./output/out-Random-progression.txt \
        ./output/out-SAHC-progression.txt \
        ./output/out-RMHC-progression.txt \
        ./output/out-RSGA-progression.txt \
        ./output/out-Christofides-progression.txt \
        shortest
python3 ./src/graph-path.py shortest $file ./output/out-Random-path.txt
python3 ./src/graph-path.py shortest $file ./output/out-Christofides-path.txt
python3 ./src/graph-path.py shortest $file ./output/out-SAHC-path.txt
python3 ./src/graph-path.py shortest $file ./output/out-RMHC-path.txt
python3 ./src/graph-path.py shortest $file ./output/out-RSGA-path.txt

mv ./output/out-Random-progression.txt ./output/out-Random-progression-lt.txt 
mv ./output/out-Random-path.txt ./output/out-Random-path-lt.txt
mv ./output/out-SAHC-progression.txt ./output/out-SAHC-progression-lt.txt
mv ./output/out-SAHC-path.txt ./output/out-SAHC-path-lt.txt
mv ./output/out-RMHC-progression.txt ./output/out-RMHC-progression-lt.txt
mv ./output/out-RMHC-path.txt ./output/out-RMHC-path-lt.txt
mv ./output/out-RSGA-progression.txt ./output/out-RSGA-progression-lt.txt
mv ./output/out-RSGA-path.txt ./output/out-RSGA-path-lt.txt

counter=0
while [ $counter -lt $num_trials ]
do
    echo
    ./tsp $file gt
    ((counter++))
    sleep 1
done

python3 ./src/graph-progression.py \
        ./output/out-Random-progression.txt \
        ./output/out-SAHC-progression.txt \
        ./output/out-RMHC-progression.txt \
        ./output/out-RSGA-progression.txt \
        longest
python3 ./src/graph-path.py longest $file ./output/out-Random-path.txt 
python3 ./src/graph-path.py longest $file ./output/out-SAHC-path.txt 
python3 ./src/graph-path.py longest $file ./output/out-RMHC-path.txt
python3 ./src/graph-path.py longest $file ./output/out-RSGA-path.txt

echo
make clean # > /dev/null 2>&1

exit 0

