#!/bin/sh

make all
if [ ! -x ./tsp ]
then
    exit 1
fi

file=

# if no file was passed to the script and res/tsp.txt exists
if [ "$#" -lt 1 -a -e ./res/tsp.txt ]
then
    file=./res/tsp.txt
elif [ -e $1 ]
then
    file=$1
else
    echo "no valid file to use" 1>&2
    exit 1
fi

counter=0
while [ $counter -lt 10 ]
do
    echo
    ./tsp $file
    ((counter++))
    sleep 2
done 

echo
make clean

exit 0

