#!/bin/sh

make all # > /dev/null 2>&1
if [ ! -x ./tsp ]
then
    exit 1
fi

rm -f out-random.txt > /dev/null 2>&1

file=

# if no file was passed to the script and res/tsp.txt exists
if [ "$#" -lt 1 -a -e ./res/tsp.txt ]
then
    file=./res/tsp.txt
elif [ -e $1 ]
then
    file=$1
else
    echo "no valid file to use" 1>&2
    exit 1
fi

counter=0
while [ $counter -lt 40 ]
do
    echo
    ./tsp $file
    ((counter++))
    sleep 1
done 

python ./src/graph.py $file out-random.txt

rm -f out-random.txt > /dev/null 2>&1

counter=0
while [ $counter -lt 40 ]
do
    echo
    ./tsp $file gt
    ((counter++))
    sleep 1
done

python ./src/graph.py $file out-random.txt

echo
make clean # > /dev/null 2>&1

exit 0

